---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
  namespace: database
data:
  maxmemory : 2mb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: database
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
       app: redis
    spec:
      containers:
      - name: redis-stack-container
        image: redis/redis-stack:latest
        ports:
          - containerPort: 6379
            name: http
          - containerPort: 8001
            name: ui
        resources:
              requests:
                   cpu: "1m"
        env:
        - name: REDIS_ARGS
          value: "--requirepass devpassword --user devuser on >devpassword ~* allcommands --user default off nopass nocommands"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: database
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-ui
  namespace: database
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001