apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: database
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
       app: kafka
    spec:
      containers:
      - name: kafka-container
        image: apache/kafka-native:latest
        ports:
          - containerPort: 9092
            name: kafka
          - containerPort: 9093
            name: kafkai
        resources:
              requests:
                   cpu: "1m"
        env:
        - name: KAFKA_LISTENERS
          value: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: HOST://localhost:9092,DOCKER://kafka:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@localhost:9091
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: DOCKER
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafkai
  namespace: database
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: servicei
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
---
# kafka ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  namespace: database
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
       app: kafka-ui
    spec:
      containers:
      - name: kafka-ui-container
        image: kafbat/kafka-ui:main
        ports:
          - containerPort: 8080
            name: kafka-ui
        resources:
              requests:
                   cpu: "1m"
        env:
        - name: DYNAMIC_CONFIG_ENABLED
          value: "true"
        - name: KAFKA_CLUSTERS_0_NAME
          value: local
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: kafkai.default.svc.cluster.local:9093
  
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: database
  labels:
    app: kafka
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: servicei
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: database
  labels:
    app: kafka-ui
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kafka-ui